# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd76a36d8f88db8b8a7a6c5a43e7a12cc8b5aaac5cadf388497db35772a1a27e8253c2bb1eba249774d985bee6952328168770ea0a9560e2edd88694d8bbd6b

test:
  secret_key_base: edce44cb67ea8f4cb4e5690e613cae00d68e2474c70bc5195dbc76b4c4846c9feb15c9e1a59c7c206897b81a7254ec9cca9b70c8f85a858c3d6a94aef4e0c695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
